const spriteData = {
	"cosmoteer.corridor": { mass: 1, size: [1, 1], cost: 0.1, tags: [""] },
	"cosmoteer.door": { size: [1, 1], cost: 0.1, tags: [""] },
	"cosmoteer.delete": { mass: 1, size: [1, 1] },
	"cosmoteer.structure": { mass: 0.33, size: [1, 1], cost: 0.05, tags: [""] },
	"cosmoteer.structure_wedge": {
		mass: 0.17,
		size: [1, 1],
		cost: 0.025,
		tags: [""],
	},
	"cosmoteer.structure_1x2_wedge": {
		mass: 0.33,
		size: [1, 2],
		cost: 0.05,
		tags: [""],
	},
	"cosmoteer.structure_1x3_wedge": {
		mass: 0.5,
		size: [1, 3],
		cost: 0.075,
		tags: [""],
	},
	"cosmoteer.structure_tri": {
		mass: 0.08,
		size: [1, 1],
		cost: 0.025,
		tags: [""],
	},
	"cosmoteer.laser_blaster_small": {
		mass: 2.5,
		size: [1, 2],
		sprite_size: [1, 4],
		dps: 667,
		burst_damage: 500,
		cost: 2,
		tags: ["weapon", "on_off"],
		cp_cost: 2,
	},
	"cosmoteer.laser_blaster_large": {
		mass: 7.68,
		size: [2, 3],
		sprite_size: [2, 6],
		dps: 1778,
		burst_damage: 1000,
		cost: 6,
		tags: ["weapon", "on_off"],
		cp_cost: 4,
	},
	"cosmoteer.disruptor": {
		mass: 3.48,
		size: [1, 3],
		sprite_size: [1, 5],
		dps: 100,
		burst_damage: 200,
		cost: 3,
		tags: ["weapon", "on_off"],
		cp_cost: 2,
	},
	"cosmoteer.ion_beam_emitter": {
		mass: 8,
		size: [2, 4],
		sprite_size: [2, 5],
		dps: 2500,
		burst_damage: 0,
		cost: 10,
		tags: ["weapon", "on_off"],
		cp_cost: 4,
	},
	"cosmoteer.resource_collector": {
		mass: 4,
		size: [2, 2],
		cost: 0,
		tags: ["on_off"],
		cp_cost: 4,
	},
	"cosmoteer.ion_beam_prism": {
		mass: 7.7,
		size: [2, 2],
		sprite_size: [2, 2.5],
		cost: 5,
		tags: [""],
		cp_cost: 2,
	},
	"cosmoteer.tractor_beam_emitter": {
		mass: 32.07,
		size: [5, 5],
		cost: 40,
		tags: ["on_off", "weapon_like"],
		cp_cost: 8,
	},
	"cosmoteer.point_defense": {
		mass: 1,
		size: [1, 1],
		sprite_size: [1, 2],
		dps: 525,
		burst_damage: 35,
		cost: 1,
		tags: ["weapon", "on_off", "fire_pref"],
		cp_cost: 1,
	},
	"cosmoteer.mining_laser_small": {
		mass: 7.4,
		size: [2, 3],
		dps: 1200,
		burst_damage: 0,
		cost: 6,
		tags: ["weapon", "on_off"],
		cp_cost: 3,
	},
	"cosmoteer.cannon_med": {
		mass: 4.44,
		size: [2, 1],
		sprite_size: [2, 3],
		dps: 1000,
		burst_damage: 750,
		cost: 2,
		tags: ["weapon", "on_off"],
		cp_cost: 2,
	},
	"cosmoteer.sensor_array": {
		mass: 11.54,
		size: [3, 3],
		cost: 20,
		tags: ["on_off"],
		cp_cost: 8,
	},
	"cosmoteer.cannon_large": {
		mass: 12.29,
		size: [3, 2],
		sprite_size: [3, 5],
		dps: 2000,
		burst_damage: 2400,
		cost: 5,
		tags: ["weapon", "on_off"],
		cp_cost: 4,
	},
	"cosmoteer.hyperdrive_beacon": {
		mass: 17.13,
		size: [4, 4],
		cost: 40,
		tags: ["on_off"],
		cp_cost: 12,
	},
	"cosmoteer.cannon_deck": {
		mass: 27.07,
		size: [4, 5],
		sprite_size: [4, 7],
		dps: 6000,
		burst_damage: 7500,
		cost: 20,
		tags: ["weapon", "on_off"],
		cp_cost: 8,
	},
	"cosmoteer.explosive_charge": {
		mass: 1,
		size: [1, 1],
		cost: 0.6,
		tags: [""],
	},
	"cosmoteer.roof_light": { mass: 1, size: [1, 1], cost: 0.2, tags: ["on_off"] },
	"cosmoteer.missile_launcher": {
		mass: 8,
		size: [2, 3],
		sprite_size: [2, 4],
		dps: 0,
		burst_damage: 0,
		cost: 10,
		tags: ["on_off"],
		cp_cost: 5,
	},
	"cosmoteer.roof_headlight": {
		mass: 1,
		size: [1, 1],
		cost: 0.3,
		tags: ["on_off"],
	},
	"cosmoteer.railgun_loader": {
		mass: 24,
		size: [2, 3],
		cost: 12.5,
		tags: ["on_off"],
		cp_cost: 4,
	},
	"cosmoteer.armor_structure_hybrid_1x1": {
		mass: 1.5,
		size: [1, 1],
		cost: 0.125,
		tags: [""],
	},
	"cosmoteer.armor_structure_hybrid_1x2": {
		mass: 3,
		size: [1, 2],
		cost: 0.25,
		tags: [""],
	},
	"cosmoteer.railgun_accelerator": {
		mass: 36,
		size: [2, 3],
		cost: 7.5,
		tags: ["on_off"],
		cp_cost: 1,
	},
	"cosmoteer.armor_structure_hybrid_1x3": {
		mass: 4.5,
		size: [1, 3],
		cost: 0.375,
		tags: [""],
	},
	"cosmoteer.armor_structure_hybrid_tri": {
		mass: 1,
		size: [1, 1],
		cost: 0.075,
		tags: [""],
	},
	"cosmoteer.railgun_launcher": {
		mass: 36,
		size: [2, 3],
		sprite_size: [2, 4],
		dps: 10000,
		burst_damage: 2500,
		cost: 7.5,
		tags: ["weapon", "on_off"],
		cp_cost: 1,
	},
	"cosmoteer.armor": { mass: 3, size: [1, 1], cost: 0.2, tags: [""] },
	"cosmoteer.armor_2x1": { mass: 6, size: [2, 1], cost: 0.4, tags: [""] },
	"cosmoteer.flak_cannon_large": {
		mass: 16.77,
		size: [3, 6],
		sprite_size: [3, 8],
		dps: 9,
		burst_damage: 2250,
		cost: 21,
		tags: ["weapon", "on_off", "fire_pref"],
		cp_cost: 6,
	},
	"cosmoteer.armor_wedge": { mass: 1.5, size: [1, 1], cost: 0.1, tags: [""] },
	"cosmoteer.armor_1x2_wedge": {
		mass: 3,
		size: [1, 2],
		cost: 0.2,
		tags: [""],
	},
	"cosmoteer.shield_gen_small": {
		mass: 6,
		size: [2, 2],
		sprite_size: [2, 3],
		cost: 5,
		tags: ["on_off"],
		cp_cost: 3,
	},
	"cosmoteer.armor_1x3_wedge": {
		mass: 4.5,
		size: [1, 3],
		cost: 0.3,
		tags: [""],
	},
	"cosmoteer.armor_tri": { mass: 0.75, size: [1, 1], cost: 0.05, tags: [""] },
	"cosmoteer.shield_gen_large": {
		mass: 12.65,
		size: [3, 6],
		cost: 20,
		tags: ["on_off"],
		cp_cost: 6,
	},
	"cosmoteer.thruster_small": {
		mass: 1.3,
		size: [1, 1],
		sprite_size: [1, 2],
		cost: 0.5,
		tags: ["thruster", "on_off"],
		cp_cost: 1,
		thrust: [0, 0, 0.4, 0],
	},
	"cosmoteer.thruster_med": {
		mass: 2.45,
		size: [1, 2],
		sprite_size: [1, 3],
		cost: 1.5,
		tags: ["thruster", "on_off"],
		cp_cost: 2,
		thrust: [0, 0, 1.2, 0],
	},
	"cosmoteer.thruster_large": {
		mass: 4.99,
		size: [2, 2],
		sprite_size: [2, 3],
		cost: 4,
		tags: ["thruster", "on_off"],
		cp_cost: 4,
		thrust: [0, 0, 3.2, 0],
	},
	"cosmoteer.thruster_boost": {
		mass: 8.88,
		size: [2, 3],
		sprite_size: [2, 5],
		cost: 6,
		tags: ["thruster", "on_off"],
		cp_cost: 6,
		thrust: [0, 0, 3.2, 0],
	},
	"cosmoteer.fire_extinguisher": {
		mass: 1,
		size: [1, 1],
		cost: 0.3,
		tags: [""],
	},
	"cosmoteer.thruster_huge": {
		mass: 11,
		size: [3, 3],
		sprite_size: [3, 5],
		cost: 10,
		tags: ["thruster", "on_off"],
		cp_cost: 8,
		thrust: [0, 0, 8, 0],
	},
	"cosmoteer.control_room_small": {
		mass: 4,
		size: [2, 2],
		cost: 10,
		tags: ["on_off"],
		cp_cost: 0,
	},
	"cosmoteer.control_room_med": {
		mass: 9,
		size: [3, 3],
		cost: 25,
		tags: ["on_off"],
		cp_cost: 0,
	},
	"cosmoteer.thruster_small_2way": {
		mass: 1.61,
		size: [1, 1],
		sprite_size: [2, 2],
		cost: 1,
		tags: ["thruster", "on_off"],
		cp_cost: 2,
		thrust: [0, 0.4, 0.4, 0],
	},
	"cosmoteer.control_room_large": {
		mass: 16,
		size: [4, 4],
		cost: 50,
		tags: ["on_off"],
		cp_cost: 0,
	},
	"cosmoteer.thruster_small_3way": {
		mass: 1.91,
		size: [1, 1],
		sprite_size: [3, 2],
		cost: 1.5,
		tags: ["thruster", "on_off"],
		cp_cost: 3,
		thrust: [0, 0.4, 0.4, 0.4],
	},
	"cosmoteer.hyperdrive_small": {
		mass: 4,
		size: [2, 2],
		cost: 10,
		tags: ["hyperdrive", "on_off"],
	},
	"cosmoteer.engine_room": {
		mass: 9,
		size: [3, 3],
		cost: 12,
		tags: ["on_off"],
		cp_cost: 6,
	},
	"cosmoteer.crew_quarters_small": {
		mass: 2,
		size: [1, 2],
		cost: 1.6,
		tags: ["crew"],
	},
	"cosmoteer.crew_quarters_med": {
		mass: 4,
		size: [2, 2],
		cost: 4.2,
		tags: ["crew"],
	},
	"cosmoteer.airlock": { mass: 1, size: [1, 1], cost: 0.6, tags: ["on_off"] },
	"cosmoteer.conveyor": { mass: 1, size: [1, 1], cost: 0.2, tags: [""] },
	"cosmoteer.reactor_small": { mass: 4, size: [2, 2], cost: 25, tags: [""] },
	"cosmoteer.reactor_med": { mass: 9, size: [3, 3], cost: 50, tags: [""] },
	"cosmoteer.reactor_large": { mass: 16, size: [4, 4], cost: 75, tags: [""] },
	"cosmoteer.power_storage": { mass: 4, size: [2, 2], cost: 4, tags: [""] },
	"cosmoteer.factory_ammo": {
		mass: 4,
		size: [2, 2],
		cost: 4.1,
		tags: ["on_off"],
		cp_cost: 1,
	},
	"cosmoteer.factory_he": {
		mass: 9,
		size: [3, 3],
		cost: 15.2,
		tags: ["on_off"],
		cp_cost: 1,
	},
	"cosmoteer.factory_emp": {
		mass: 12,
		size: [3, 4],
		cost: 20.5,
		tags: ["on_off"],
		cp_cost: 1,
	},
	"cosmoteer.factory_nuke": {
		mass: 16,
		size: [4, 4],
		cost: 27.1,
		tags: ["on_off"],
		cp_cost: 1,
	},
	"cosmoteer.factory_mine": {
		mass: 12,
		size: [4, 3],
		cost: 20.18,
		tags: ["on_off"],
		cp_cost: 1,
	},
	"cosmoteer.factory_steel": {
		mass: 16,
		size: [4, 4],
		cost: 30.4,
		tags: ["on_off"],
		cp_cost: 1,
	},
	"cosmoteer.factory_coil": {
		mass: 9,
		size: [3, 3],
		cost: 30.8,
		tags: ["on_off"],
		cp_cost: 1,
	},
	"cosmoteer.factory_coil2": {
		mass: 12,
		size: [4, 3],
		cost: 54.8,
		tags: ["on_off"],
		cp_cost: 1,
	},
	"cosmoteer.factory_tristeel": {
		mass: 16,
		size: [4, 4],
		cost: 68.2,
		tags: ["on_off"],
		cp_cost: 1,
	},
	"cosmoteer.factory_diamond": {
		mass: 6,
		size: [2, 3],
		cost: 53.2,
		tags: ["on_off"],
		cp_cost: 1,
	},
	"cosmoteer.factory_processor": {
		mass: 9,
		size: [3, 3],
		cost: 89,
		tags: ["on_off"],
		cp_cost: 1,
	},
	"cosmoteer.factory_uranium": {
		mass: 12,
		size: [3, 4],
		cost: 98,
		tags: ["on_off"],
		cp_cost: 1,
	},
	"cosmoteer.storage_2x2": { mass: 4, size: [2, 2], cost: 1.2, tags: [""] },
	"cosmoteer.storage_3x2": { mass: 6, size: [3, 2], cost: 1.8, tags: [""] },
	"cosmoteer.storage_3x3": { mass: 9, size: [3, 3], cost: 2.7, tags: [""] },
	"cosmoteer.storage_4x3": { mass: 12, size: [4, 3], cost: 3.6, tags: [""] },
	"cosmoteer.storage_4x4": { mass: 16, size: [4, 4], cost: 4.8, tags: [""] },
	"cosmoteer.chaingun": {
		mass: 17.77,
		size: [3, 5],
		sprite_size: [3, 7],
		dps: 18000,
		burst_damage: 0,
		cost: 24,
		tags: ["weapon", "on_off"],
		cp_cost: 6,
	},
	"cosmoteer.chaingun_magazine": {
		mass: 2,
		size: [1, 2],
		cost: 1,
		tags: [""],
	},
	"cosmoteer.hyperdrive_large": {
		mass: 16,
		size: [4, 4],
		cost: 34,
		tags: ["hyperdrive", "on_off"],
	},
	"cosmoteer.thruster_rocket_battery": {
		mass: 2,
		size: [1, 2],
		cost: 3,
		tags: [""],
	},
	"cosmoteer.thruster_rocket_extender": {
		mass: 6,
		size: [3, 2],
		cost: 6,
		tags: ["thruster", "on_off"],
		thrust: [0, 0, 8, 0],
	},
	"cosmoteer.thruster_rocket_nozzle": {
		mass: 14.4,
		size: [3, 4],
		sprite_size: [3, 5],
		cost: 15,
		tags: ["thruster", "on_off"],
		cp_cost: 16,
		thrust: [0, 0, 8, 0],
	},
	"cosmoteer.hyperdrive_med": {
		mass: 9,
		size: [3, 3],
		cost: 20,
		tags: ["hyperdrive", "on_off"],
	},
	"cosmoteer.manipulator_beam_emitter": {
		mass: 4,
		size: [2, 2],
		cost: 3,
		tags: ["on_off"],
		cp_cost: 4,
	},
	"cosmoteer.crew_quarters_large": {
		mass: 12,
		size: [3, 4],
		cost: 15.6,
		tags: ["crew"],
	},
};
const upTurrets = [
	"cosmoteer.laser_blaster_small",
	"cosmoteer.laser_blaster_large",
	"cosmoteer.disruptor",
	"cosmoteer.ion_beam_emitter",
	"cosmoteer.ion_beam_prism",
	"cosmoteer.point_defense",
	"cosmoteer.cannon_med",
	"cosmoteer.cannon_large",
	"cosmoteer.cannon_deck",
	"cosmoteer.missile_launcher",
	"cosmoteer.railgun_launcher",
	"cosmoteer.flak_cannon_large",
	"cosmoteer.shield_gen_small",
	"cosmoteer.chaingun",
];
const downTurrets = [
	"cosmoteer.thruster_small",
	"cosmoteer.thruster_med",
	"cosmoteer.thruster_large",
	"cosmoteer.thruster_huge",
	"cosmoteer.thruster_boost",
];
const mergingParts = [
	"cosmoteer.corridor",
	"cosmoteer.conveyor"
]

const multiple_turrets = [
	"cosmoteer.thruster_small_2way",
	"cosmoteer.thruster_small_3way",
];

//A single corridor block
const startup_ship_data = {"Author": "Plaus", "BuildCenterlineNESW": null, "BuildCenterlineNWSE": null, "BuildCenterlineX": null, "BuildCenterlineY": null, "BuildMirrorAxis": 1, "BuildMirrorEnabled": false, "CrewSourceRoles": "Unset", "CrewSourceTargets": "Unset", "Decals1": "Unset", "Decals2": "Unset", "Decals3": "Unset", "DefaultAttackFollowAngle": null, "DefaultAttackRadius": null, "DefaultAttackRotation": null, "Description": "", "Doors": "Unset", "FlightDirection": 1, "FormationOrder": 3, "Name": "Unnamed Ship", "NewFlexResourceGridTypes": "Unset", "PaintCenterlineNESW": null, "PaintCenterlineNWSE": null, "PaintCenterlineX": null, "PaintCenterlineY": null, "PaintMirrorAxis": 1, "PaintMirrorEnabled": false, "PartControlGroups": "Unset", "Parts": [{"FlipX": false, "ID": "cosmoteer.corridor", "Location": [-1, 0], "Rotation": 0}], "PartUIColorValues": "Unset", "PartUIToggleStates": "Unset", "ResourceConsumptionToggles": "Unset", "ResourceSupplierTargets": "Unset", "ResourceSupplyToggles": "Unset", "Roles": [{"AssignmentPriority": 5, "AutoFillFromLower": true, "Color": ["D093943E", "00000000", "D678583F", "0000803F"], "ID": -2147483648, "Name": "Supply", "Priorities": [{"Key": {"ComponentID": "PartCrew", "PartID": "cosmoteer.laser_blaster_small"}, "Value": 0}, {"Key": {"ComponentID": "PartCrew", "PartID": "cosmoteer.laser_blaster_large"}, "Value": 0}, {"Key": {"ComponentID": "PartCrew", "PartID": "cosmoteer.disruptor"}, "Value": 0}, {"Key": {"ComponentID": "PartCrew", "PartID": "cosmoteer.ion_beam_emitter"}, "Value": 0}, {"Key": {"ComponentID": "PartCrew", "PartID": "cosmoteer.cannon_med"}, "Value": 0}, {"Key": {"ComponentID": "BatteryConsumer", "PartID": "cosmoteer.thruster_small"}, "Value": 5}, {"Key": {"ComponentID": "PartCrew", "PartID": "cosmoteer.cannon_large"}, "Value": 0}, {"Key": {"ComponentID": "PartCrew", "PartID": "cosmoteer.cannon_deck"}, "Value": 0}, {"Key": {"ComponentID": "PartCrew", "PartID": "cosmoteer.missile_launcher"}, "Value": 0}, {"Key": {"ComponentID": "PartCrew", "PartID": "cosmoteer.railgun_loader"}, "Value": 0}, {"Key": {"ComponentID": "PartCrew", "PartID": "cosmoteer.chaingun"}, "Value": 0}, {"Key": {"ComponentID": "BatteryConsumer", "PartID": "cosmoteer.shield_gen_small"}, "Value": 8}, {"Key": {"ComponentID": "BatteryConsumer", "PartID": "cosmoteer.shield_gen_large"}, "Value": 8}, {"Key": {"ComponentID": "PartCrew", "PartID": "cosmoteer.flak_cannon_large"}, "Value": 0}, {"Key": {"ComponentID": "BatteryConsumer", "PartID": "cosmoteer.point_defense"}, "Value": 3}, {"Key": {"ComponentID": "FireExtinguishJob", "PartID": "cosmoteer.fire_extinguisher"}, "Value": 9}, {"Key": {"ComponentID": "PartCrew", "PartID": "cosmoteer.control_room_large"}, "Value": 0}, {"Key": {"ComponentID": "BatteryConsumer", "PartID": "cosmoteer.control_room_small"}, "Value": 9}, {"Key": {"ComponentID": "PartCrew", "PartID": "cosmoteer.control_room_med"}, "Value": 0}, {"Key": {"ComponentID": "BatteryConsumer", "PartID": "cosmoteer.control_room_med"}, "Value": 9}, {"Key": {"ComponentID": "PartCrew", "PartID": "cosmoteer.control_room_small"}, "Value": 0}, {"Key": {"ComponentID": "BatteryConsumer", "PartID": "cosmoteer.control_room_large"}, "Value": 9}, {"Key": {"ComponentID": "BatteryConsumer", "PartID": "cosmoteer.thruster_small_2way"}, "Value": 5}, {"Key": {"ComponentID": "BatteryConsumer", "PartID": "cosmoteer.thruster_small_3way"}, "Value": 5}, {"Key": {"ComponentID": "BatteryConsumer", "PartID": "cosmoteer.thruster_med"}, "Value": 5}, {"Key": {"ComponentID": "BatteryConsumer", "PartID": "cosmoteer.thruster_boost"}, "Value": 7}, {"Key": {"ComponentID": "BatteryConsumer", "PartID": "cosmoteer.thruster_huge"}, "Value": 7}, {"Key": {"ComponentID": "BatteryConsumer", "PartID": "cosmoteer.thruster_large"}, "Value": 7}, {"Key": {"ComponentID": "BatteryConsumer", "PartID": "cosmoteer.engine_room"}, "Value": 7}, {"Key": {"ComponentID": "BatteryConsumer", "PartID": "cosmoteer.hyperdrive_small"}, "Value": 8}, {"Key": {"ComponentID": "BatteryConsumer", "PartID": "cosmoteer.hyperdrive_med"}, "Value": 8}, {"Key": {"ComponentID": "BatteryConsumer", "PartID": "cosmoteer.hyperdrive_large"}, "Value": 8}, {"Key": {"ComponentID": "ResourceTransferJob.Collect", "PartID": "cosmoteer.crew_quarters_med"}, "Value": 1}, {"Key": {"ComponentID": "SalvageJob", "PartID": "cosmoteer.crew_quarters_med"}, "Value": 1}, {"Key": {"ComponentID": "ConstructPartJob", "PartID": "cosmoteer.crew_quarters_med"}, "Value": 1}, {"Key": {"ComponentID": "DeconstructJob", "PartID": "cosmoteer.crew_quarters_med"}, "Value": 1}, {"Key": {"ComponentID": "RepairPartJob", "PartID": "cosmoteer.crew_quarters_med"}, "Value": 1}, {"Key": {"ComponentID": "BatteryConsumer", "PartID": "cosmoteer.power_storage"}, "Value": 3}, {"Key": {"ComponentID": "SulfurConsumer", "PartID": "cosmoteer.factory_ammo"}, "Value": 5}, {"Key": {"ComponentID": "BatteryConsumer", "PartID": "cosmoteer.factory_ammo"}, "Value": 5}, {"Key": {"ComponentID": "IronConsumer", "PartID": "cosmoteer.factory_he"}, "Value": 5}, {"Key": {"ComponentID": "SulfurConsumer", "PartID": "cosmoteer.factory_he"}, "Value": 5}, {"Key": {"ComponentID": "BatteryConsumer", "PartID": "cosmoteer.factory_he"}, "Value": 5}, {"Key": {"ComponentID": "IronConsumer", "PartID": "cosmoteer.factory_emp"}, "Value": 5}, {"Key": {"ComponentID": "CopperConsumer", "PartID": "cosmoteer.factory_emp"}, "Value": 5}, {"Key": {"ComponentID": "BatteryConsumer", "PartID": "cosmoteer.factory_emp"}, "Value": 5}, {"Key": {"ComponentID": "IronConsumer", "PartID": "cosmoteer.factory_nuke"}, "Value": 5}, {"Key": {"ComponentID": "UraniumConsumer", "PartID": "cosmoteer.factory_nuke"}, "Value": 5}, {"Key": {"ComponentID": "BatteryConsumer", "PartID": "cosmoteer.factory_nuke"}, "Value": 5}, {"Key": {"ComponentID": "IronConsumer", "PartID": "cosmoteer.factory_mine"}, "Value": 2}, {"Key": {"ComponentID": "AmmoConsumer", "PartID": "cosmoteer.factory_mine"}, "Value": 2}, {"Key": {"ComponentID": "BatteryConsumer", "PartID": "cosmoteer.factory_mine"}, "Value": 2}, {"Key": {"ComponentID": "IronConsumer", "PartID": "cosmoteer.factory_steel"}, "Value": 2}, {"Key": {"ComponentID": "BatteryConsumer", "PartID": "cosmoteer.factory_steel"}, "Value": 2}, {"Key": {"ComponentID": "CopperConsumer", "PartID": "cosmoteer.factory_coil"}, "Value": 2}, {"Key": {"ComponentID": "BatteryConsumer", "PartID": "cosmoteer.factory_coil"}, "Value": 2}, {"Key": {"ComponentID": "CoilConsumer", "PartID": "cosmoteer.factory_coil2"}, "Value": 2}, {"Key": {"ComponentID": "CopperConsumer", "PartID": "cosmoteer.factory_coil2"}, "Value": 2}, {"Key": {"ComponentID": "BatteryConsumer", "PartID": "cosmoteer.factory_coil2"}, "Value": 2}, {"Key": {"ComponentID": "TritaniumConsumer", "PartID": "cosmoteer.factory_tristeel"}, "Value": 2}, {"Key": {"ComponentID": "BatteryConsumer", "PartID": "cosmoteer.factory_tristeel"}, "Value": 2}, {"Key": {"ComponentID": "CarbonConsumer", "PartID": "cosmoteer.factory_diamond"}, "Value": 2}, {"Key": {"ComponentID": "BatteryConsumer", "PartID": "cosmoteer.factory_diamond"}, "Value": 2}, {"Key": {"ComponentID": "CoilConsumer", "PartID": "cosmoteer.factory_processor"}, "Value": 2}, {"Key": {"ComponentID": "GoldConsumer", "PartID": "cosmoteer.factory_processor"}, "Value": 2}, {"Key": {"ComponentID": "BatteryConsumer", "PartID": "cosmoteer.factory_processor"}, "Value": 2}, {"Key": {"ComponentID": "UraniumConsumer", "PartID": "cosmoteer.factory_uranium"}, "Value": 2}, {"Key": {"ComponentID": "BatteryConsumer", "PartID": "cosmoteer.factory_uranium"}, "Value": 2}, {"Key": {"ComponentID": "BatteryConsumer", "PartID": "cosmoteer.mining_laser_small"}, "Value": 6}, {"Key": {"ComponentID": "PartCrew", "PartID": "cosmoteer.resource_collector"}, "Value": 0}, {"Key": {"ComponentID": "BatteryConsumer", "PartID": "cosmoteer.resource_collector"}, "Value": 5}, {"Key": {"ComponentID": "PartCrew", "PartID": "cosmoteer.tractor_beam_emitter"}, "Value": 0}, {"Key": {"ComponentID": "PartCrew", "PartID": "cosmoteer.sensor_array"}, "Value": 0}, {"Key": {"ComponentID": "BatteryConsumer", "PartID": "cosmoteer.sensor_array"}, "Value": 7}, {"Key": {"ComponentID": "PartCrew", "PartID": "cosmoteer.hyperdrive_beacon"}, "Value": 0}, {"Key": {"ComponentID": "BatteryConsumer", "PartID": "cosmoteer.laser_blaster_small"}, "Value": 6}, {"Key": {"ComponentID": "BatteryConsumer", "PartID": "cosmoteer.laser_blaster_large"}, "Value": 6}, {"Key": {"ComponentID": "BatteryConsumer", "PartID": "cosmoteer.disruptor"}, "Value": 6}, {"Key": {"ComponentID": "BatteryConsumer", "PartID": "cosmoteer.ion_beam_emitter"}, "Value": 6}, {"Key": {"ComponentID": "PartCrew", "PartID": "cosmoteer.mining_laser_small"}, "Value": 0}, {"Key": {"ComponentID": "AmmoConsumer", "PartID": "cosmoteer.cannon_med"}, "Value": 6}, {"Key": {"ComponentID": "AmmoConsumer", "PartID": "cosmoteer.cannon_large"}, "Value": 6}, {"Key": {"ComponentID": "AmmoConsumer", "PartID": "cosmoteer.cannon_deck"}, "Value": 6}, {"Key": {"ComponentID": "MissileStorage", "PartID": "cosmoteer.missile_launcher"}, "Value": 6}, {"Key": {"ComponentID": "EMPMissilesComponents", "PartID": "cosmoteer.missile_launcher"}, "Value": 6}, {"Key": {"ComponentID": "NukeMissilesComponents", "PartID": "cosmoteer.missile_launcher"}, "Value": 6}, {"Key": {"ComponentID": "MinesComponents", "PartID": "cosmoteer.missile_launcher"}, "Value": 6}, {"Key": {"ComponentID": "AmmoConsumer", "PartID": "cosmoteer.railgun_loader"}, "Value": 6}, {"Key": {"ComponentID": "BatteryConsumer", "PartID": "cosmoteer.railgun_accelerator"}, "Value": 6}, {"Key": {"ComponentID": "BatteryConsumer", "PartID": "cosmoteer.railgun_launcher"}, "Value": 6}, {"Key": {"ComponentID": "AmmoConsumerLeft", "PartID": "cosmoteer.chaingun"}, "Value": 6}, {"Key": {"ComponentID": "AmmoConsumer", "PartID": "cosmoteer.chaingun_magazine"}, "Value": 6}, {"Key": {"ComponentID": "AmmoConsumer", "PartID": "cosmoteer.flak_cannon_large"}, "Value": 6}, {"Key": {"ComponentID": "PartCrew", "PartID": "cosmoteer.engine_room"}, "Value": 0}, {"Key": {"ComponentID": "BatteryConsumer", "PartID": "cosmoteer.tractor_beam_emitter"}, "Value": 7}, {"Key": {"ComponentID": "BatteryConsumer", "PartID": "cosmoteer.hyperdrive_beacon"}, "Value": 5}, {"Key": {"ComponentID": "HyperiumConsumer", "PartID": "cosmoteer.hyperdrive_med"}, "Value": 5}, {"Key": {"ComponentID": "HyperiumConsumer", "PartID": "cosmoteer.hyperdrive_large"}, "Value": 5}, {"Key": {"ComponentID": "flex_grid_uranium", "PartID": "cosmoteer.storage_2x2"}, "Value": 2}, {"Key": {"ComponentID": "flex_grid_gold", "PartID": "cosmoteer.storage_2x2"}, "Value": 2}, {"Key": {"ComponentID": "flex_grid_bullet", "PartID": "cosmoteer.storage_2x2"}, "Value": 2}, {"Key": {"ComponentID": "flex_grid_missile_part_he", "PartID": "cosmoteer.storage_2x2"}, "Value": 2}, {"Key": {"ComponentID": "flex_grid_missile_part_nuke", "PartID": "cosmoteer.storage_2x2"}, "Value": 2}, {"Key": {"ComponentID": "flex_grid_mine_part", "PartID": "cosmoteer.storage_2x2"}, "Value": 2}, {"Key": {"ComponentID": "flex_grid_missile_part_emp", "PartID": "cosmoteer.storage_2x2"}, "Value": 2}, {"Key": {"ComponentID": "flex_grid_steel", "PartID": "cosmoteer.storage_2x2"}, "Value": 2}, {"Key": {"ComponentID": "flex_grid_coil2", "PartID": "cosmoteer.storage_2x2"}, "Value": 2}, {"Key": {"ComponentID": "flex_grid_tristeel", "PartID": "cosmoteer.storage_2x2"}, "Value": 2}, {"Key": {"ComponentID": "flex_grid_coil", "PartID": "cosmoteer.storage_2x2"}, "Value": 2}, {"Key": {"ComponentID": "flex_grid_diamond", "PartID": "cosmoteer.storage_2x2"}, "Value": 2}, {"Key": {"ComponentID": "flex_grid_processor", "PartID": "cosmoteer.storage_2x2"}, "Value": 2}, {"Key": {"ComponentID": "flex_grid_sulfur", "PartID": "cosmoteer.storage_2x2"}, "Value": 2}, {"Key": {"ComponentID": "flex_grid_enriched_uranium", "PartID": "cosmoteer.storage_2x2"}, "Value": 2}, {"Key": {"ComponentID": "flex_grid_iron", "PartID": "cosmoteer.storage_2x2"}, "Value": 2}, {"Key": {"ComponentID": "flex_grid_copper", "PartID": "cosmoteer.storage_2x2"}, "Value": 2}, {"Key": {"ComponentID": "flex_grid_tritanium", "PartID": "cosmoteer.storage_2x2"}, "Value": 2}, {"Key": {"ComponentID": "flex_grid_carbon", "PartID": "cosmoteer.storage_2x2"}, "Value": 2}, {"Key": {"ComponentID": "flex_grid_hyperium", "PartID": "cosmoteer.storage_2x2"}, "Value": 2}, {"Key": {"ComponentID": "HyperiumConsumer", "PartID": "cosmoteer.hyperdrive_small"}, "Value": 5}, {"Key": {"ComponentID": "PartCrew", "PartID": "cosmoteer.thruster_rocket_nozzle"}, "Value": 0}, {"Key": {"ComponentID": "BatteryConsumer", "PartID": "cosmoteer.thruster_rocket_battery"}, "Value": 6}, {"Key": {"ComponentID": "BatteryConsumer", "PartID": "cosmoteer.thruster_rocket_extender"}, "Value": 7}, {"Key": {"ComponentID": "BatteryConsumer", "PartID": "cosmoteer.thruster_rocket_nozzle"}, "Value": 7}]}], "RoofBaseColor": ["00000000", "00000000", "00000000", "00000000"], "RoofBaseTexture": "_none_", "RoofDecalColor1": ["0000803F", "0000803F", "0000803F", "0000803F"], "RoofDecalColor2": ["0000003F", "0000003F", "0000003F", "0000803F"], "RoofDecalColor3": ["0000803F", "00000000", "00000000", "0000803F"], "ShipRulesID": "cosmoteer.terran", "Version": 3, "WeaponDirectControlBindings": "Unset", "WeaponSelfTargets": "Unset", "WeaponShipRelativeTargets": "Unset"}
